apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: maintenance-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    docker-kafka-cluster:
                      properties:
                        bootstrap.servers: "kafka-svc:9092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akhq-svc
  namespace: maintenance-match
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
  selector:
    app: akhq