server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth
  # --- Kafka Configurations ---
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  # --- Database Configuration ---
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USER:ds_user}
    password: ${DB_PASS:ds_pass}
  # --- JPA & Hibernate Configuration ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# --- Actuator Health Endpoint Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info" # Expose health and info endpoints
  endpoint:
    health:
      show-details: always # Show full details (e.g., DB connection status)
      probes:
        enabled: true # Enables Kubernetes-style readiness/liveness probes

# --- Custom Application Properties ---
app:
  kafka:
    topics:
      notification-send: ${NOTIFICATION_TOPIC:notification.send}
      maintainer-profile-creation: ${MAINTAINER_TOPIC:maintainer-profile-creation}
  clients:
    matching-url: ${MATCHING_URL:http://localhost:8082}
    notification-url: ${NOTIFICATION_URL:http://localhost:8083}
  jwt:
    secret-key-path: "keys/private.key"
    access-token-expiration-ms: 900000   # 15 minutes
    refresh-token-expiration-ms: 604800000 # 7 days


api-gateway:
  url: ${API_GATEWAY_URL:http://localhost:8080}