server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: matching
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  # --- Database Configuration ---
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/maintenance_match_db}
    username: ${DB_USER:ds_user}
    password: ${DB_PASS:ds_pass}
  # --- JPA & Hibernate Configuration ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# --- Actuator Health Endpoint Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# --- Custom Application Properties ---
app:
  clients:
    auth-url: ${AUTH_URL:http://localhost:8081}
  kafka:
    topics:
      notification-send: ${NOTIFICATION_TOPIC:notification.send}

api-gateway:
  url: ${API_GATEWAY_URL:http://localhost:8080}