apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: maintenance-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: kidushawoltu/ds-mm-auth:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom: { configMapKeyRef: { name: mm-config, key: AUTH_DB_URL } }
            - name: DB_USER
              valueFrom: { configMapKeyRef: { name: mm-config, key: DB_USER } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: mm-secrets, key: DB_PASS } }
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom: { configMapKeyRef: { name: mm-config, key: KAFKA_BOOTSTRAP_SERVERS } }
            - name: SERVER_PORT
              value: "8081"
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8081 }
            initialDelaySeconds: 30
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8081 }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: maintenance-match
spec:
  selector:
    app: auth
  ports:
    - port: 8081
      targetPort: 8081