apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-app
  namespace: maintenance-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: kidushawoltu/ds-mm-matching:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom: { configMapKeyRef: { name: mm-config, key: MATCHING_DB_URL } }
            - name: DB_USER
              valueFrom: { configMapKeyRef: { name: mm-config, key: DB_USER } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: mm-secrets, key: DB_PASS } }
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom: { configMapKeyRef: { name: mm-config, key: KAFKA_BOOTSTRAP_SERVERS } }
            - name: AUTH_URL
              valueFrom: { configMapKeyRef: { name: mm-config, key: AUTH_URL } }
            - name: NOTIFICATION_URL
              valueFrom: { configMapKeyRef: { name: mm-config, key: NOTIFICATION_URL } }
            - name: SERVER_PORT
              value: "8082"
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8082 }
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: matching-svc
  namespace: maintenance-match
spec:
  selector:
    app: matching
  ports:
    - port: 8082
      targetPort: 8082